server {
  listen 80;
  server_name _;

  server_tokens off;

  location / {
    root   /usr/share/nginx/smart-schedule;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
}